from __future__ import annotations

from typing import Any

from ..models import TaskNode, Workflow
from ._common import art, publish
from .doc_context import product_name, requirement_text
from .llm_bridge import run_llm_agent


def documentation_write(wf: Workflow, task: TaskNode) -> dict[str, Any]:
    """12. Documentation Agent — engineering docs from artifacts + PRD."""
    llm = run_llm_agent(
        wf,
        task,
        agent="documentation",
        inputs={
            "hld": art(wf, "hld"),
            "adrs": art(wf, "adrs"),
            "openapi": art(wf, "openapi"),
            "test_plan": art(wf, "test_plan"),
        },
        schema_hint='{"documentation":{"readme":"","runbooks":[],"architecture_document":""}}',
    )
    if llm and isinstance(llm.get("documentation"), dict):
        docs = llm["documentation"]
        publish(wf, task, "documentation", docs, bill=False)
        if "workload_dashboards" not in wf.artifacts:
            publish(
                wf,
                task,
                "workload_dashboards",
                {"panels": ["redirect_p99", "cache_hit_ratio", "error_rate"]},
                bill=False,
            )
        return {
            "summary": f"Documentation via LLM for {product_name(wf)}",
            "mode": "llm",
        }

    name = product_name(wf)
    hld = art(wf, "hld") or {}
    docs = {
        "product": name,
        "readme": f"{name} — scalable URL shortener (generated by Forge from uploaded PRD)",
        "architecture_document": hld.get("style")
        or "Cache-first redirect; async analytics via Kafka",
        "design_decisions": "See ADRs artifact",
        "runbooks": [
            "redirect_latency_spike",
            "cache_stampede",
            "kafka_lag",
            "rate_limit_storm",
        ],
        "deployment_guide": "Staging via CI; prod canary 5→25→50→100",
        "developer_guide": "Local compose: link-api, redirect-api, redis, postgres",
        "api_documentation": "openapi rendered + examples",
        "testing_guide": "unit + contract + k6 under tests/load",
        "operations_guide": "SLOs, on-call, error budgets",
        "source_prd_excerpt": (requirement_text(wf) or "")[:500],
    }
    if wf.facts.get("feature_qr"):
        docs["runbooks"].append("qr_service_errors")
    publish(wf, task, "documentation", docs)
    if "workload_dashboards" not in wf.artifacts:
        publish(
            wf,
            task,
            "workload_dashboards",
            {"panels": ["redirect_p99", "cache_hit_ratio", "error_rate", "kafka_lag"]},
        )
    return {"summary": f"Documentation for {name}: {len(docs['runbooks'])} runbooks + guides"}
